"""YAML configuration generator producing standard ULPF mapping.yaml files."""

import yaml
from typing import Any, Dict, List, Optional
from .detector_heuristics import DetectedFormatResult
from .semantic_analyzer import SemanticAnalysisResult


class IndentedDumper(yaml.SafeDumper):
    """Custom YAML Dumper for clean list indentations."""
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


class YamlGenerator:
    """Generates standard ULPF YAML mapping draft configurations with review headers."""

    def generate_yaml(
        self,
        format_result: DetectedFormatResult,
        semantic_result: SemanticAnalysisResult,
        source_name: str = "Unknown Device",
        product_name: Optional[str] = None,
        confidence_label: Optional[str] = None,
    ) -> str:
        """Construct the complete mapping.yaml content as a YAML string with banner comment."""
        conf_label = confidence_label or semantic_result.confidence_label

        # 1. Header Banner
        header = (
            "# ⚠️ AUTO-GENERATED DRAFT — not yet reviewed by a human\n"
            "# Generated by: Auto-Mapping Assistant\n"
            f"# Confidence: {conf_label} — see notes below\n"
            "# Review checklist:\n"
            "#   - Verify field_map targets are semantically correct, not just structurally plausible\n"
            "#   - Verify classification rules match real device behavior, not just this sample\n"
            "#   - Verify timestamp format/timezone\n"
            '#   - Once reviewed, remove this header and move status to "reviewed" in source_identity\n\n'
        )

        vendor = source_name.strip()
        product = (product_name or source_name).strip()

        # 2. Source Identity
        source_identity = {
            "vendor": vendor,
            "product": product,
            "format": format_result.format_type,
            "version": "1.0",
            "status": "draft",
        }

        # 3. Detection Block
        detection: Dict[str, Any] = {"method": format_result.detection_method}
        if format_result.detection_conditions:
            detection["conditions"] = format_result.detection_conditions
        elif format_result.detection_pattern:
            detection["pattern"] = format_result.detection_pattern
        else:
            detection["pattern"] = r'^\S+'

        # 4. Parsing Block
        parsing: Dict[str, Any] = {}
        fmt = format_result.format_type

        if fmt == "space_delimited":
            parsing["delimiter"] = format_result.delimiter or " "
            parsing["skip_line_prefix"] = "#"
            fields_dict = {}
            for k, v in semantic_result.field_definitions.items():
                if k.startswith("col_"):
                    try:
                        idx = int(k.replace("col_", ""))
                        fields_dict[idx] = v
                    except ValueError:
                        fields_dict[k] = v
                else:
                    fields_dict[k] = v
            parsing["fields"] = fields_dict

        elif fmt in ("csv", "delimited"):
            parsing["delimiter"] = format_result.delimiter or ","
            if format_result.has_header:
                parsing["header"] = True
            fields_dict = {}
            for k, v in semantic_result.field_definitions.items():
                if k.startswith("col_"):
                    try:
                        idx = int(k.replace("col_", ""))
                        fields_dict[idx] = v
                    except ValueError:
                        fields_dict[k] = v
                else:
                    fields_dict[k] = v
            parsing["fields"] = fields_dict

        elif fmt == "json":
            parsing["format"] = "json"
            parsing["fields"] = {k: v for k, v in semantic_result.field_definitions.items()}

        elif fmt == "key_value":
            parsing["format"] = "key_value"
            parsing["fields"] = {k: v for k, v in semantic_result.field_definitions.items()}

        elif fmt == "syslog":
            parsing["format"] = "syslog"
            parsing["header"] = {
                "pattern": r'^(?:<\d+>)?(?P<raw_timestamp>[A-Za-z]{3}\s+\d+\s+\d{2}:\d{2}:\d{2})\s+(?P<raw_host>[^\s:]+)\s+',
                "fields": {
                    "raw_timestamp": "raw_timestamp",
                    "raw_host": "raw_host",
                },
            }
            parsing["body"] = {"target": "raw_message"}
        else:
            parsing["delimiter"] = " "
            parsing["fields"] = semantic_result.field_definitions

        # 5. Classification Block
        classification: Dict[str, Any] = {
            "default_class_uid": semantic_result.default_class_uid,
            "default_class_name": semantic_result.default_class_name,
        }
        if semantic_result.classification_rules:
            classification["rules"] = semantic_result.classification_rules

        # 6. Field Map
        field_map = semantic_result.field_map

        # 7. Static Fields
        static_fields = semantic_result.static_fields

        # 8. Transforms
        transforms = semantic_result.transforms

        # 9. Timestamp
        timestamp = semantic_result.timestamp_config

        # 10. Unmapped & Raw Preservation
        unmapped_policy = semantic_result.unmapped_policy
        raw_preservation = semantic_result.raw_preservation

        config_dict = {
            "source_identity": source_identity,
            "detection": detection,
            "parsing": parsing,
            "classification": classification,
            "field_map": field_map,
            "static_fields": static_fields,
            "transforms": transforms,
            "timestamp": timestamp,
            "unmapped_policy": unmapped_policy,
            "raw_preservation": raw_preservation,
        }

        yaml_body = yaml.dump(
            config_dict,
            Dumper=IndentedDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

        return header + yaml_body
